### ISSUE TITLE
Crash client local multiplayer game.

### ISSUE THREAD

**Issue by Furiolis** [Sinhika/Fusion#16] opened 2022-01-27 20:32 UTC
[crash-2022-01-27_21.07.07-client.txt](https://github.com/Sinhika/Fusion/files/7953578/crash-2022-01-27_21.07.07-client.txt)
Local multiplayer game.
Host can use Fusion Furnace freely. 
Client crash when put in tin, copper, coal, anything.
Minecraft 1.16.5
Forge 36.2.22
Fusion-1.16.5-2.7.4.4

**Comment by Sinhika** [comment] 2022-01-28 15:35
Does it work if you test with ONLY SimpleCoreLib, SimpleOres2, Fusion and JEI?

**Comment by Furiolis** [comment] 2022-01-28 21:54
Same situation
[crash-2022-01-28_22.51.53-client.txt](https://github.com/Sinhika/Fusion/files/7962024/crash-2022-01-28_22.51.53-client.txt)
.

**Comment by Sinhika** [comment] 2022-03-14 00:39
Duplicate of #15

**Closed as completed by Sinhika** 2022-03-14 00:39 UTC
